"""Qt bridge for AppState Observable events."""
from PySide6.QtCore import QObject, Signal
from data_graph_studio.core.state import AppState


class AppStateAdapter(QObject):
    """Bridges AppState Observable events to Qt Signals for UI consumption."""

    data_loaded = Signal()
    data_cleared = Signal()
    group_zone_changed = Signal()
    value_zone_changed = Signal()
    hover_zone_changed = Signal()
    filter_changed = Signal()
    sort_changed = Signal()
    selection_changed = Signal()
    limit_to_marking_changed = Signal(bool)
    chart_settings_changed = Signal()
    tool_mode_changed = Signal()
    grid_view_changed = Signal()
    summary_updated = Signal(dict)
    profile_loaded = Signal(object)
    profile_cleared = Signal()
    profile_saved = Signal()
    setting_activated = Signal(str)
    setting_added = Signal(str)
    setting_removed = Signal(str)
    floating_window_opened = Signal(str)
    floating_window_closed = Signal(str)
    dataset_added = Signal(str)
    dataset_removed = Signal(str)
    dataset_activated = Signal(str)
    dataset_updated = Signal(str)
    comparison_mode_changed = Signal(str)
    comparison_settings_changed = Signal()

    def __init__(self, state: AppState, parent: QObject = None):
        super().__init__(parent)
        self._state = state
        state.subscribe("data_loaded", self.data_loaded.emit)
        state.subscribe("data_cleared", self.data_cleared.emit)
        state.subscribe("group_zone_changed", self.group_zone_changed.emit)
        state.subscribe("value_zone_changed", self.value_zone_changed.emit)
        state.subscribe("hover_zone_changed", self.hover_zone_changed.emit)
        state.subscribe("filter_changed", self.filter_changed.emit)
        state.subscribe("sort_changed", self.sort_changed.emit)
        state.subscribe("selection_changed", self.selection_changed.emit)
        state.subscribe("limit_to_marking_changed", self.limit_to_marking_changed.emit)
        state.subscribe("chart_settings_changed", self.chart_settings_changed.emit)
        state.subscribe("tool_mode_changed", self.tool_mode_changed.emit)
        state.subscribe("grid_view_changed", self.grid_view_changed.emit)
        state.subscribe("summary_updated", self.summary_updated.emit)
        state.subscribe("profile_loaded", self.profile_loaded.emit)
        state.subscribe("profile_cleared", self.profile_cleared.emit)
        state.subscribe("profile_saved", self.profile_saved.emit)
        state.subscribe("setting_activated", self.setting_activated.emit)
        state.subscribe("setting_added", self.setting_added.emit)
        state.subscribe("setting_removed", self.setting_removed.emit)
        state.subscribe("floating_window_opened", self.floating_window_opened.emit)
        state.subscribe("floating_window_closed", self.floating_window_closed.emit)
        state.subscribe("dataset_added", self.dataset_added.emit)
        state.subscribe("dataset_removed", self.dataset_removed.emit)
        state.subscribe("dataset_activated", self.dataset_activated.emit)
        state.subscribe("dataset_updated", self.dataset_updated.emit)
        state.subscribe("comparison_mode_changed", self.comparison_mode_changed.emit)
        state.subscribe("comparison_settings_changed", self.comparison_settings_changed.emit)
